image: cirrusci/flutter:stable

stages:
  - build_android

before_script:
  - flutter pub get
  - flutter clean
  - flutter --version

build_android:
 stage: build_android
 before_script:
   - flutter packages get
   - flutter clean
 script:
   - flutter build apk
 artifacts:
   paths:
     - build/app/outputs/apk/release/app-release.apk
